# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\"\n\x05point\x12\x0b\n\x03lat\x18\x01 \x01(\x05\x12\x0c\n\x04lang\x18\x02 \x01(\x05\"\x18\n\tdirection\x12\x0b\n\x03\x64ir\x18\x01 \x01(\t*/\n\x03\x44ir\x12\t\n\x05North\x10\x00\x12\t\n\x05South\x10\x01\x12\x08\n\x04\x45\x61st\x10\x02\x12\x08\n\x04West\x10\x03\x32)\n\x07Routing\x12\x1e\n\x08getRoute\x12\x06.point\x1a\n.directionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DIR']._serialized_start=76
  _globals['_DIR']._serialized_end=123
  _globals['_POINT']._serialized_start=14
  _globals['_POINT']._serialized_end=48
  _globals['_DIRECTION']._serialized_start=50
  _globals['_DIRECTION']._serialized_end=74
  _globals['_ROUTING']._serialized_start=125
  _globals['_ROUTING']._serialized_end=166
# @@protoc_insertion_point(module_scope)
